### ISSUE TITLE
ReadMe uses A.T, causing error of demo code snippet

### ISSUE THREAD

**Issue by mattlevine22** [rgklab/StructuredNNs#5]
StrNN function documentation says ":param adjacency: the adjacency matrix, nout by nin", but ReadME code demo uses "in_dim = A.shape[0], out_dim = A.shape[1]". The ReadMe code errors; it appears that the StrNN function doc string is correct.

**Comment by a19c97** [comment]
Thanks for pointing out the error! You're correct that the readme was wrong while the StrNN model documentation was right. We have amended the readme to reflect this.
